In [31]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


Then, we run some setup code for this notebook: Import some useful packages and increase the default figure size.

In [32]:
# install required libraries

# need scipy for writing wav files
!pip install numpy matplotlib scipy

# import libraries
import math
import numpy as np
import matplotlib.pyplot as plt

# set figure size
plt.rcParams['figure.figsize'] = (5.0, 4.0)
plt.rcParams['font.size'] = 10
%config InlineBackend.figure_format = 'retina'

In [33]:
from IPython.display import display_html, HTML

display_html(HTML('''
<style type="text/css">
  .instruction { background-color: yellow; font-weight:bold; padding: 3px; }
</style>
'''));

In [35]:
import ica
ica.hello()   # should print "Hello from ica.py!"

Hello from ica.py!


## Load Data

Let's load the sound data. This data contains mixed sound signals from multiple microphones.

In [36]:
from IPython.display import Audio, display

Fs = 11025  # sampling rate
def normalize(dat):
    return 0.99 * dat / np.max(np.abs(dat))

mix = np.loadtxt('data/ica_data.dat')
X = normalize(mix)
print(f'Loaded {X.shape[0] / Fs:.2f} seconds of audio with {X.shape[1]} microphones.')

Loaded 4.85 seconds of audio with 5 microphones.


In [37]:
for i in range(X.shape[1]):
    print(f'Microphone {i}:')
    display(Audio(X[:, i], rate=Fs))

Microphone 0:


Microphone 1:


Microphone 2:


Microphone 3:


Microphone 4:


## Learning the filter *W*

<p class="instruction">Implement the `ica.filter_grad()` function. </p>

This function computes the SGD update for ICA. This function will be used with `ica.unmixer` to find a filter `W` that we can use to unmix our sources `X`.

The following code should take around up to 1~2 minutes to run.

In [38]:
%%time

W = ica.unmixer(X)
print('W solution:\n', W)

Separating tracks ...
working on alpha = 0.1
working on alpha = 0.1
working on alpha = 0.1
working on alpha = 0.05
working on alpha = 0.05
working on alpha = 0.05
working on alpha = 0.02
working on alpha = 0.02
working on alpha = 0.01
working on alpha = 0.01
working on alpha = 0.005
working on alpha = 0.005
working on alpha = 0.002
working on alpha = 0.002
working on alpha = 0.001
working on alpha = 0.001
W solution:
 [[ 72.15081922  28.62441682  25.91040458 -17.2322227  -21.191357  ]
 [ 13.45886116  31.94398247  -4.03003982 -24.0095722   11.89906179]
 [ 18.89688784  -7.80435173  28.71469558  18.14356811 -21.17474522]
 [ -6.0119837   -4.15743607  -1.01692289  13.87321073  -5.26252289]
 [ -8.74061186  22.55821897   9.61289023  14.73637074  45.28841827]]
CPU times: user 40.9 s, sys: 2.14 s, total: 43 s
Wall time: 8.52 s


## Unmixing with *W*
<p class="instruction">Implement the `ica.unmix` function. </p> 

Let's use our `W` to unmix our original sources `X`!

In [31]:
S = normalize(ica.unmix(X, W))

In [32]:
for i in range(X.shape[1]):
    print(f'Unmixed source {i}:')
    display(Audio(S[:, i], rate=Fs))

Unmixed source 0:


Unmixed source 1:


Unmixed source 2:


Unmixed source 3:


Unmixed source 4:


How does it sound? Some overlap in sources may be present, but the sound sources should be pretty clearly separated. If you still hear some significant overlap, something is probably wrong in your implementation...

## Saving the unmixed sources

## Submission

<p class="instruction">Report the *W* matrix you found in your final report. Submit this file along with ica.py to the autograder.</p> 
Make sure your unmixed source sound tracks are playable when you submit. These audio files will be embedded in the notebook and we may check these files when grading. You do <b>not</b> need to submit the saved unmixed `wav` tracks!